### ISSUE TITLE
Lag switching among animations when using dynamic loading

### ISSUE THREAD

**Issue by mdenchev** [mdenchev/bevy_aseprite#3]
This is in reference to https://github.com/TheNeikos/bevy_spicy_aseprite/issues/6.

Hi @lemunozm, I enabled issues on the forked repo (didn't know they get turned off by default). I don't believe there should be any difference between manually specifying animations or using the derived version which makes me think this is a system ordering issue. Is the lag 1-frame long?

**Comment by lemunozm** [comment]
Hi @mdenchev , the lag I'm seeing is about 200-300 milliseconds which implies several frames in my aseprite. It is apreciable in each animation transition.

I will try to offer a small reproducible example (maybe tomorrow).

**Comment by lemunozm** [comment]
Hi @mdenchev, I did more investigation:

- bevy_aseprite (dynamic): I see the issue.
- bevy_aseprite (derive): I see the issue.
- bevy_spicy_aseprite: I do not see the issue.

I checked that `process_load()` is only called at configuration time and it is, so the problem does not seem to come from reading the sprite from the disk when changing the animation.

Also, I noticed that `AsepriteAnimation::update()` stores the `time_elapsed`. If the AsepriteAnimation is changed by a new one, the `time_elapsed` will be 0 again, and the first image (that will be the second frame) will be rendered after the time of the first frame, instead of instantly as expected when I change an animation. Probably this is what I'm experimenting with: my first frame is skipped and I see an extra wait corresponding with the "first frame time of the new animation", then I can see the new animation but start in the second frame.

**Comment by mdenchev** [comment]
Thanks for the write up! I will try to get out a fix tonight. I think the
solution is to add a flag that an animation is new to the
AsepriteAnimations struct and in the update step to switch to the first
frame of the animation if that flag is on.

**Comment by mdenchev** [comment]
I pushed what I think should be a fix to main. Do you mind testing it @lemunozm ?

**Comment by lemunozm** [comment]
Tested! 😃 

Now it works as expected, without lag. Thank you so much!
